# Generated by Django 4.1.5 on 2023-02-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_post_caption_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='dp',
            field=models.ImageField(null=True, upload_to='dp/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post/'),
        ),
    ]
